bse_analytics:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'analytics'
      schema: 'main'
      schemas_and_paths:
        main: '/opt/airflow/data/announcements.db'
      schema_directory: '/opt/airflow/data'
