name: 'bse_analytics'
version: '1.0.0'
config-version: 2

profile: 'bse_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  bse_analytics:
    staging:
      +materialized: view
    analytics:
      +materialized: table
